// Code generated by ent, DO NOT EDIT.

package round

import (
	"golfapp/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Round {
	return predicate.Round(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Round {
	return predicate.Round(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Round {
	return predicate.Round(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Round {
	return predicate.Round(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Round {
	return predicate.Round(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Round {
	return predicate.Round(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Round {
	return predicate.Round(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Round {
	return predicate.Round(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Round {
	return predicate.Round(sql.FieldLTE(FieldID, id))
}

// DateOfRound applies equality check predicate on the "date_of_round" field. It's identical to DateOfRoundEQ.
func DateOfRound(v time.Time) predicate.Round {
	return predicate.Round(sql.FieldEQ(FieldDateOfRound, v))
}

// DateOfRoundEQ applies the EQ predicate on the "date_of_round" field.
func DateOfRoundEQ(v time.Time) predicate.Round {
	return predicate.Round(sql.FieldEQ(FieldDateOfRound, v))
}

// DateOfRoundNEQ applies the NEQ predicate on the "date_of_round" field.
func DateOfRoundNEQ(v time.Time) predicate.Round {
	return predicate.Round(sql.FieldNEQ(FieldDateOfRound, v))
}

// DateOfRoundIn applies the In predicate on the "date_of_round" field.
func DateOfRoundIn(vs ...time.Time) predicate.Round {
	return predicate.Round(sql.FieldIn(FieldDateOfRound, vs...))
}

// DateOfRoundNotIn applies the NotIn predicate on the "date_of_round" field.
func DateOfRoundNotIn(vs ...time.Time) predicate.Round {
	return predicate.Round(sql.FieldNotIn(FieldDateOfRound, vs...))
}

// DateOfRoundGT applies the GT predicate on the "date_of_round" field.
func DateOfRoundGT(v time.Time) predicate.Round {
	return predicate.Round(sql.FieldGT(FieldDateOfRound, v))
}

// DateOfRoundGTE applies the GTE predicate on the "date_of_round" field.
func DateOfRoundGTE(v time.Time) predicate.Round {
	return predicate.Round(sql.FieldGTE(FieldDateOfRound, v))
}

// DateOfRoundLT applies the LT predicate on the "date_of_round" field.
func DateOfRoundLT(v time.Time) predicate.Round {
	return predicate.Round(sql.FieldLT(FieldDateOfRound, v))
}

// DateOfRoundLTE applies the LTE predicate on the "date_of_round" field.
func DateOfRoundLTE(v time.Time) predicate.Round {
	return predicate.Round(sql.FieldLTE(FieldDateOfRound, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Round) predicate.Round {
	return predicate.Round(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Round) predicate.Round {
	return predicate.Round(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Round) predicate.Round {
	return predicate.Round(func(s *sql.Selector) {
		p(s.Not())
	})
}
