// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golfapp/ent/hole"
	"golfapp/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HoleUpdate is the builder for updating Hole entities.
type HoleUpdate struct {
	config
	hooks    []Hook
	mutation *HoleMutation
}

// Where appends a list predicates to the HoleUpdate builder.
func (hu *HoleUpdate) Where(ps ...predicate.Hole) *HoleUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// SetHoleNumber sets the "hole_number" field.
func (hu *HoleUpdate) SetHoleNumber(i int) *HoleUpdate {
	hu.mutation.ResetHoleNumber()
	hu.mutation.SetHoleNumber(i)
	return hu
}

// AddHoleNumber adds i to the "hole_number" field.
func (hu *HoleUpdate) AddHoleNumber(i int) *HoleUpdate {
	hu.mutation.AddHoleNumber(i)
	return hu
}

// SetHoleName sets the "hole_name" field.
func (hu *HoleUpdate) SetHoleName(s string) *HoleUpdate {
	hu.mutation.SetHoleName(s)
	return hu
}

// Mutation returns the HoleMutation object of the builder.
func (hu *HoleUpdate) Mutation() *HoleMutation {
	return hu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HoleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hu.sqlSave, hu.mutation, hu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HoleUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HoleUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HoleUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (hu *HoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(hole.Table, hole.Columns, sqlgraph.NewFieldSpec(hole.FieldID, field.TypeInt))
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hu.mutation.HoleNumber(); ok {
		_spec.SetField(hole.FieldHoleNumber, field.TypeInt, value)
	}
	if value, ok := hu.mutation.AddedHoleNumber(); ok {
		_spec.AddField(hole.FieldHoleNumber, field.TypeInt, value)
	}
	if value, ok := hu.mutation.HoleName(); ok {
		_spec.SetField(hole.FieldHoleName, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hu.mutation.done = true
	return n, nil
}

// HoleUpdateOne is the builder for updating a single Hole entity.
type HoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HoleMutation
}

// SetHoleNumber sets the "hole_number" field.
func (huo *HoleUpdateOne) SetHoleNumber(i int) *HoleUpdateOne {
	huo.mutation.ResetHoleNumber()
	huo.mutation.SetHoleNumber(i)
	return huo
}

// AddHoleNumber adds i to the "hole_number" field.
func (huo *HoleUpdateOne) AddHoleNumber(i int) *HoleUpdateOne {
	huo.mutation.AddHoleNumber(i)
	return huo
}

// SetHoleName sets the "hole_name" field.
func (huo *HoleUpdateOne) SetHoleName(s string) *HoleUpdateOne {
	huo.mutation.SetHoleName(s)
	return huo
}

// Mutation returns the HoleMutation object of the builder.
func (huo *HoleUpdateOne) Mutation() *HoleMutation {
	return huo.mutation
}

// Where appends a list predicates to the HoleUpdate builder.
func (huo *HoleUpdateOne) Where(ps ...predicate.Hole) *HoleUpdateOne {
	huo.mutation.Where(ps...)
	return huo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HoleUpdateOne) Select(field string, fields ...string) *HoleUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated Hole entity.
func (huo *HoleUpdateOne) Save(ctx context.Context) (*Hole, error) {
	return withHooks(ctx, huo.sqlSave, huo.mutation, huo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HoleUpdateOne) SaveX(ctx context.Context) *Hole {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HoleUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HoleUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (huo *HoleUpdateOne) sqlSave(ctx context.Context) (_node *Hole, err error) {
	_spec := sqlgraph.NewUpdateSpec(hole.Table, hole.Columns, sqlgraph.NewFieldSpec(hole.FieldID, field.TypeInt))
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hole.FieldID)
		for _, f := range fields {
			if !hole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := huo.mutation.HoleNumber(); ok {
		_spec.SetField(hole.FieldHoleNumber, field.TypeInt, value)
	}
	if value, ok := huo.mutation.AddedHoleNumber(); ok {
		_spec.AddField(hole.FieldHoleNumber, field.TypeInt, value)
	}
	if value, ok := huo.mutation.HoleName(); ok {
		_spec.SetField(hole.FieldHoleName, field.TypeString, value)
	}
	_node = &Hole{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	huo.mutation.done = true
	return _node, nil
}
