// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golfapp/ent/hole"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HoleCreate is the builder for creating a Hole entity.
type HoleCreate struct {
	config
	mutation *HoleMutation
	hooks    []Hook
}

// SetHoleNumber sets the "hole_number" field.
func (hc *HoleCreate) SetHoleNumber(i int) *HoleCreate {
	hc.mutation.SetHoleNumber(i)
	return hc
}

// SetHoleName sets the "hole_name" field.
func (hc *HoleCreate) SetHoleName(s string) *HoleCreate {
	hc.mutation.SetHoleName(s)
	return hc
}

// Mutation returns the HoleMutation object of the builder.
func (hc *HoleCreate) Mutation() *HoleMutation {
	return hc.mutation
}

// Save creates the Hole in the database.
func (hc *HoleCreate) Save(ctx context.Context) (*Hole, error) {
	return withHooks(ctx, hc.sqlSave, hc.mutation, hc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HoleCreate) SaveX(ctx context.Context) *Hole {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HoleCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HoleCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HoleCreate) check() error {
	if _, ok := hc.mutation.HoleNumber(); !ok {
		return &ValidationError{Name: "hole_number", err: errors.New(`ent: missing required field "Hole.hole_number"`)}
	}
	if _, ok := hc.mutation.HoleName(); !ok {
		return &ValidationError{Name: "hole_name", err: errors.New(`ent: missing required field "Hole.hole_name"`)}
	}
	return nil
}

func (hc *HoleCreate) sqlSave(ctx context.Context) (*Hole, error) {
	if err := hc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	hc.mutation.id = &_node.ID
	hc.mutation.done = true
	return _node, nil
}

func (hc *HoleCreate) createSpec() (*Hole, *sqlgraph.CreateSpec) {
	var (
		_node = &Hole{config: hc.config}
		_spec = sqlgraph.NewCreateSpec(hole.Table, sqlgraph.NewFieldSpec(hole.FieldID, field.TypeInt))
	)
	if value, ok := hc.mutation.HoleNumber(); ok {
		_spec.SetField(hole.FieldHoleNumber, field.TypeInt, value)
		_node.HoleNumber = value
	}
	if value, ok := hc.mutation.HoleName(); ok {
		_spec.SetField(hole.FieldHoleName, field.TypeString, value)
		_node.HoleName = value
	}
	return _node, _spec
}

// HoleCreateBulk is the builder for creating many Hole entities in bulk.
type HoleCreateBulk struct {
	config
	builders []*HoleCreate
}

// Save creates the Hole entities in the database.
func (hcb *HoleCreateBulk) Save(ctx context.Context) ([]*Hole, error) {
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Hole, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HoleCreateBulk) SaveX(ctx context.Context) []*Hole {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HoleCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HoleCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
