// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"golfapp/ent/tee"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Tee is the model entity for the Tee schema.
type Tee struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Color holds the value of the "color" field.
	Color string `json:"color,omitempty"`
	// HoleName holds the value of the "hole_name" field.
	HoleName     int `json:"hole_name,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tee) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tee.FieldID, tee.FieldHoleName:
			values[i] = new(sql.NullInt64)
		case tee.FieldColor:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tee fields.
func (t *Tee) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tee.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case tee.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				t.Color = value.String
			}
		case tee.FieldHoleName:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hole_name", values[i])
			} else if value.Valid {
				t.HoleName = int(value.Int64)
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tee.
// This includes values selected through modifiers, order, etc.
func (t *Tee) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// Update returns a builder for updating this Tee.
// Note that you need to call Tee.Unwrap() before calling this method if this Tee
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Tee) Update() *TeeUpdateOne {
	return NewTeeClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Tee entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Tee) Unwrap() *Tee {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tee is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Tee) String() string {
	var builder strings.Builder
	builder.WriteString("Tee(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("color=")
	builder.WriteString(t.Color)
	builder.WriteString(", ")
	builder.WriteString("hole_name=")
	builder.WriteString(fmt.Sprintf("%v", t.HoleName))
	builder.WriteByte(')')
	return builder.String()
}

// Tees is a parsable slice of Tee.
type Tees []*Tee
