// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golfapp/ent/predicate"
	"golfapp/ent/tee"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TeeUpdate is the builder for updating Tee entities.
type TeeUpdate struct {
	config
	hooks    []Hook
	mutation *TeeMutation
}

// Where appends a list predicates to the TeeUpdate builder.
func (tu *TeeUpdate) Where(ps ...predicate.Tee) *TeeUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetColor sets the "color" field.
func (tu *TeeUpdate) SetColor(s string) *TeeUpdate {
	tu.mutation.SetColor(s)
	return tu
}

// SetHoleName sets the "hole_name" field.
func (tu *TeeUpdate) SetHoleName(i int) *TeeUpdate {
	tu.mutation.ResetHoleName()
	tu.mutation.SetHoleName(i)
	return tu
}

// AddHoleName adds i to the "hole_name" field.
func (tu *TeeUpdate) AddHoleName(i int) *TeeUpdate {
	tu.mutation.AddHoleName(i)
	return tu
}

// Mutation returns the TeeMutation object of the builder.
func (tu *TeeUpdate) Mutation() *TeeMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TeeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TeeUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TeeUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TeeUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TeeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tee.Table, tee.Columns, sqlgraph.NewFieldSpec(tee.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Color(); ok {
		_spec.SetField(tee.FieldColor, field.TypeString, value)
	}
	if value, ok := tu.mutation.HoleName(); ok {
		_spec.SetField(tee.FieldHoleName, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedHoleName(); ok {
		_spec.AddField(tee.FieldHoleName, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TeeUpdateOne is the builder for updating a single Tee entity.
type TeeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeeMutation
}

// SetColor sets the "color" field.
func (tuo *TeeUpdateOne) SetColor(s string) *TeeUpdateOne {
	tuo.mutation.SetColor(s)
	return tuo
}

// SetHoleName sets the "hole_name" field.
func (tuo *TeeUpdateOne) SetHoleName(i int) *TeeUpdateOne {
	tuo.mutation.ResetHoleName()
	tuo.mutation.SetHoleName(i)
	return tuo
}

// AddHoleName adds i to the "hole_name" field.
func (tuo *TeeUpdateOne) AddHoleName(i int) *TeeUpdateOne {
	tuo.mutation.AddHoleName(i)
	return tuo
}

// Mutation returns the TeeMutation object of the builder.
func (tuo *TeeUpdateOne) Mutation() *TeeMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TeeUpdate builder.
func (tuo *TeeUpdateOne) Where(ps ...predicate.Tee) *TeeUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TeeUpdateOne) Select(field string, fields ...string) *TeeUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Tee entity.
func (tuo *TeeUpdateOne) Save(ctx context.Context) (*Tee, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TeeUpdateOne) SaveX(ctx context.Context) *Tee {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TeeUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TeeUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TeeUpdateOne) sqlSave(ctx context.Context) (_node *Tee, err error) {
	_spec := sqlgraph.NewUpdateSpec(tee.Table, tee.Columns, sqlgraph.NewFieldSpec(tee.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tee.FieldID)
		for _, f := range fields {
			if !tee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Color(); ok {
		_spec.SetField(tee.FieldColor, field.TypeString, value)
	}
	if value, ok := tuo.mutation.HoleName(); ok {
		_spec.SetField(tee.FieldHoleName, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedHoleName(); ok {
		_spec.AddField(tee.FieldHoleName, field.TypeInt, value)
	}
	_node = &Tee{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
