// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golfapp/ent/tee"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TeeCreate is the builder for creating a Tee entity.
type TeeCreate struct {
	config
	mutation *TeeMutation
	hooks    []Hook
}

// SetColor sets the "color" field.
func (tc *TeeCreate) SetColor(s string) *TeeCreate {
	tc.mutation.SetColor(s)
	return tc
}

// SetHoleName sets the "hole_name" field.
func (tc *TeeCreate) SetHoleName(i int) *TeeCreate {
	tc.mutation.SetHoleName(i)
	return tc
}

// Mutation returns the TeeMutation object of the builder.
func (tc *TeeCreate) Mutation() *TeeMutation {
	return tc.mutation
}

// Save creates the Tee in the database.
func (tc *TeeCreate) Save(ctx context.Context) (*Tee, error) {
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TeeCreate) SaveX(ctx context.Context) *Tee {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TeeCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TeeCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TeeCreate) check() error {
	if _, ok := tc.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "Tee.color"`)}
	}
	if _, ok := tc.mutation.HoleName(); !ok {
		return &ValidationError{Name: "hole_name", err: errors.New(`ent: missing required field "Tee.hole_name"`)}
	}
	return nil
}

func (tc *TeeCreate) sqlSave(ctx context.Context) (*Tee, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TeeCreate) createSpec() (*Tee, *sqlgraph.CreateSpec) {
	var (
		_node = &Tee{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(tee.Table, sqlgraph.NewFieldSpec(tee.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Color(); ok {
		_spec.SetField(tee.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if value, ok := tc.mutation.HoleName(); ok {
		_spec.SetField(tee.FieldHoleName, field.TypeInt, value)
		_node.HoleName = value
	}
	return _node, _spec
}

// TeeCreateBulk is the builder for creating many Tee entities in bulk.
type TeeCreateBulk struct {
	config
	builders []*TeeCreate
}

// Save creates the Tee entities in the database.
func (tcb *TeeCreateBulk) Save(ctx context.Context) ([]*Tee, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Tee, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TeeCreateBulk) SaveX(ctx context.Context) []*Tee {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TeeCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TeeCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
