// Code generated by ent, DO NOT EDIT.

package tee

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tee type in the database.
	Label = "tee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldColor holds the string denoting the color field in the database.
	FieldColor = "color"
	// FieldHoleName holds the string denoting the hole_name field in the database.
	FieldHoleName = "hole_name"
	// Table holds the table name of the tee in the database.
	Table = "tees"
)

// Columns holds all SQL columns for tee fields.
var Columns = []string{
	FieldID,
	FieldColor,
	FieldHoleName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Tee queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByColor orders the results by the color field.
func ByColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldColor, opts...).ToFunc()
}

// ByHoleName orders the results by the hole_name field.
func ByHoleName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHoleName, opts...).ToFunc()
}
