// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// Hole is the predicate function for hole builders.
type Hole func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)

// Round is the predicate function for round builders.
type Round func(*sql.Selector)

// Tee is the predicate function for tee builders.
type Tee func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
